name: Java-CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2
      - run: chmod +x ci/build-app.sh && ci/build-app.sh
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
  - name: Download a single artifact
    uses: actions/download-artifact@v2
    with:
      name: code
      path: .
    needs: Clone-down
    run: ci/unit-test-app.sh

  Build:
  - name: Download a single artifact
  uses: actions/download-artifact@v2
  with:
    name: code
    path: .
    - needs: Clone-down
    - uses: actions/upload-artifact@v2
      with:
        name: code
        path: .

