name: Java-CI
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps: 
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - run: bash ci/unit-test-app.sh

  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Build
      run: bash ci/build-app.sh
    - uses: actions/upload-artifact@v2
      with:
        name: code
        path: .

  Docker-image: 
    needs: [Test, Build]
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Build Docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/build-docker.sh
    - name: Push Docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/push-docker.sh
  
  Component-test: 
    needs: Docker-image
    runs-on: ubuntu-latest
    steps:
    - name: run-component-test
      run: bash ci/component-test.sh
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .

      

      
